---

- name: Repository key (Debian)
  apt_key:
    state=present
    url="{{mr_repository_key}}"
  
- name: NewRelic Repository (Debian)
  apt_repository:
    state=present
    repo="deb {{nr_repository}} {{ansible_distribution_release}} main"
    update_cache=yes

- name: Install NewRelic System Monitor (Debian)
  apt:
    state="{{ (nr_upgrade) | ternary('latest', 'present') }}"
    name="{{nr_packages}}"

# vi:ts=2:sw=2:et:ft=yaml
