---
#
# 
#

- name: NewRelic apt key
  apt_key: 
    url={{newrelic.apt.key}} 
    state=present

- name: NewRelic apt repository
  apt_repository:
    repo="deb {{newrelic.apt.repository}}"
    state=present
  register: repository

- name: NewRelic update cache
  apt:
    update_cache=yes
  when: repository.changed

# vi:ts=2:sw=2:et:ft=yaml
